apiVersion: v2
name: espocrm
description: A Helm chart for deploying EspoCRM on Kubernetes
type: application
version: 1.1.0
appVersion: "9.1.0"
sources:
  - https://github.com/TWENTY-20/helm-charts/tree/main/espocrm
keywords:
  - espocrm
  - crm
  - helm
  - kubernetes