kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.data.name }}
  annotations:
    everest.io/disk-volume-type: {{ .Values.persistence.data.storageType }}
spec:
  storageClassName: {{ .Values.persistence.data.storageClass }}
  accessModes: {{ .Values.persistence.data.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.storageSize }}
